# Generated by Django 4.0.4 on 2022-04-19 00:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='plato'),
        ),
    ]
